README.md, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceOwnerResolver.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceHandlerTest.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationResourceOwnerResolutionStrategy.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationResourceOwnerResolutionStrategyTest.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt
- resolving resource owner eagerly at mark time
=> refactor(notifications): Updated how resource owner is resolved

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/AmazonTagExclusionPolicy.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/model/AmazonResource.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-clouddriver/src/main/kotlin/com/netflix/spinnaker/swabbie/clouddriver/ClouddriverAccountProvider.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieConfiguration.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Cacheable.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceProvider.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/AccountConfigurationExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/NameExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Account.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Application.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/configuration/AccountExclusionPolicyTest.kt, swabbie-edda/src/main/kotlin/com/netflix/spinnaker/swabbie/edda/securitygroups/EddaAmazonSecurityGroupProvider.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationCache.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicy.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationResourceOwnerResolutionStrategyTest.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/config/DynomiteConfiguration.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt
- Favor a generic provider than impl for each resource provider
- Javadocs and better logging
- remove hardcoded stuff meant for testing locally
- caching applications fetched
- getting started on an application exclusion policy that will help with opting out resources
- fixed a typo bug in NotificationAgent
=> refactor(*): refactoring

README.md, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/rules.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieConfiguration.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Cacheable.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTagger.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateEventListener.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Application.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notificationMessages.kt, swabbie-echo/src/main/kotlin/com/netflix/spinnaker/swabbie/echo/EchoNotifier.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/tagging/EntityTag.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/tagging/ResourceEntityTagger.kt
- refactor notifications & tagging
=> refactor(*): Misc refactoring

README.md, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
- updated readme
- renamed scopeOfWork to work
=> chore(readme): Updated readme

swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/Main.kt
- fixing a copy/pasta typo in the main class
=> fix(configuration): fixing a copy/pasta typo

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceHandlerTest.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/config/DynomiteConfiguration.kt, swabbie-test/src/main/kotlin/com/netflix/spinnaker/swabbie/test/TestResource.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt
=> refactor(*): misc cleanups and refactor

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/SwabbieAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkProcessor.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgentTest.kt
- pass a complete fx to the handler to call once work is completed
=> fix(*): fixing releasing lock prematurely

swabbie-core/src/main/kotlin/com/netflix/spinnaker/SwabbieAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgentTest.kt
- gauge for marked candidates
- refactor agent.run.age
=> fix(metrics): metrics cleanup

README.md, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/WorkConfiguratorTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgentTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManagerTest.kt
- unit test & corresponding refactoring
- renaming of some classes
=> chore(*): misc refactor & unit test

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AgentRunner.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/LockManager.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisLockManager.kt
- recording a number of the handlers metrics
=> chore(metrics): Adding metrics

swabbie-core/src/main/kotlin/com/netflix/spinnaker/SwabbieAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieConfiguration.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceOwnerResolver.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceProvider.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgentTest.kt, swabbie-edda/src/main/kotlin/com/netflix/spinnaker/swabbie/edda/EddaResourceProviders.kt
- adding some simple retries around edda (TODO: lift common retry logic coming soon)
=> chore(*): Adding retries to rest calls

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AgentRunner.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/SwabbieAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt
- moved SwabbieAgent to agent package in core
=> chore(agent): Move Agent interface to proper package

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgentTest.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt
- using projectedDeletion time as the only marker for when things get deleted
- only update notification info when a notification is sent
=> refactor(*): Adding a boolean field for notification

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/AmazonTagOwnerResolutionStrategy.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/AmazonTagOwnerResolutionStrategyTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceOwnerResolver.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategy.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategyTest.kt
- added type def to resource owner resolver
=> refactor(*): Typifying owner resolver

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/AccountExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/NameExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Application.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicy.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicyTest.kt
=> feat(*): Adding support for whitelisting

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/LockingConfigurationProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/LockingService.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/LockingConfiguration.kt
- configurable locking properties
=> refactor(locking): Make locking configurable

build.gradle, gradle.properties, gradle/kotlin.gradle, swabbie-core/swabbie-core.gradle, swabbie-retrofit/src/main/kotlin/com/netflix/spinnaker/swabbie/retrofit/SwabbieRetrofitConfiguration.kt
=> chore(dependencies): Update kotlin dependencies & misc

README.md, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt, swabbie-retrofit/src/main/kotlin/com/netflix/spinnaker/swabbie/retrofit/SwabbieRetrofitConfiguration.kt
- removed unused okhttpconfig import
=> refactor(*): Updated read me and some new lines

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/MetricsSupport.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/SwabbieAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt
=> refactor(*): Moved some common metrics to a class

README.md, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/SwabbieAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt
- remove redundancy between agents process method
- add a note about locking
- distinct agents allow for finer grain manipulation
=> refactor(*): Simplify agents

swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaService.kt
- strong typing response from orca
=> refactor(orca): Strong type orca response

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaService.kt
- ensure to resolve owner before deleting a resource
=> fix(delete): Ensure owner resolved before delete

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroup.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/Rules.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceDisabledServerGroupRuleTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceInDiscoveryDisabledServerGroupRuleTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandler.kt
- allows cleaning of leftover disabled server groups from red/black
=> feat(servergroups): Adding support for server group deletions

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt
- use region instead of regions
=> fix(image): Fix typo in region field

README.md, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroup.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImage.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/instances/AmazonInstance.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/LaunchConfiguration.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonElasticLoadBalancer.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/model/AmazonResource.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroup.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceDisabledServerGroupRuleTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceInDiscoveryDisabledServerGroupRuleTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/exclusions/AmazonTagExclusionPolicyTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/WorkConfiguratorTest.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategyTest.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt, swabbie-test/src/main/kotlin/com/netflix/spinnaker/swabbie/test/TestResource.kt
- retentionDays renamed to retention
- added a maxAge in order to compare against a resource creation stamp
- added a creationDate for all aws resources
- updated tests
=> refactor(*): renaming retentionDays to just retention

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroup.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/instances/AmazonInstance.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/LaunchConfiguration.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/model/AmazonResource.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceDisabledServerGroupRuleTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceInDiscoveryDisabledServerGroupRuleTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt
- different resources have different createDate
=> fix(*): use instance launctime, asg createtime & launch config createtime

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/model/AmazonResource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Dates.kt, swabbie-edda/src/main/kotlin/com/netflix/spinnaker/swabbie/edda/EddaService.kt
- expanding edda field to include dates
- formatting different dates format for resources
=> fix(dates): Adding a utility class to parse dates

swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
=> chore(test): Disable this test to unblock travis

swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
=> fix(controller): optOut changed to PUT

swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
- fixing a test Travis was not happy with
=> chore(test): reenable test

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- Resolving owners synchronously
=> chore(core): Resolving owners synchronously

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/MetricsSupport.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManagerTest.kt
- also updated optout to use the correct metric counter
- added test for optout
=> chore(core): Update tests for `ResourceStateManager`

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- add more info to result print
- changed info to debug when skipping opted out candidate
=> chore(core): Formatting result log

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/Rules.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- in addition to labels and exclusion. special case to find base amis
=> chore(images): Follow ancestor tree to find base images

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt
- Fixes a concurrency bug in the Image Handler caused by multiple async classifiers updating a non-threadsafe data structure
- Log ImageId, name, and region for each classification
=> fix(images): synchronously run image classifiers

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- chained image classifiers won't duplicate work
=> feat(core): prefilter resources by maxAge

swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicyTest.kt
=> chore(test): Adding unit test for exclusion by allowList

swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
- marked resources is not nullable, returns empty list
=> chore(controller): Specifying return as non nullable

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceOwnerResolver.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Application.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategy.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategyTest.kt
Porting the OSS changes from https://github.com/spinnaker/swabbie/pull/98/ around allowing multiple owners.
=> feat(owners): allow multiple owners (port from #98)

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- implement delete images
- update core to fetch resources eagerly in one call
- refactor delete to be more efficient
- adapt tests
=> feat(deleteImage): Delete image

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt
- remove unnecessary runBlocking block
=> chore(deleteAsg): remove unnecessary runBlocking block

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceTrackingManager.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt
I was asked to look at the metrics, but nothing really popped out as missing. I did cleanup a bunch of logs in the process, though.
=> chore(*): Cleanup of main-path logs

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonElasticLoadBalancerProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonImageProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonSecurityGroupProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAutoScalingGroupProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaImagesUsedByInstancesProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaInstanceProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationCacheProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceProvider.kt
Using an object, with fields and types and such.
=> chore(params): map to actual object

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
cleaning up indentation, and removing some of the nested logic that `.let{}` promotes. Pulling those things to named variables.
=> chore(handler): refactor doMark and doDelete

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepository.kt
Dynomite doesn't support transactions
=> fix(redis): don't use transactions because dynomite

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisConfiguration.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisTaskTrackingRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt
reading in chunks of 100 from redis instead of unlimited size
=> fix(redis): read in smaller chunks

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt
=> fix(redis): get num marked resources uses correct call

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
Right now notifications can contain images in different families (like both swabbie and clouddriver images) if they have the same owner. This PR groups the list by `grouping` value so that the resulting notifications contain only images in the same group (now swabbie and clouddriver would each get their own email).
Also de-nesting some areas for clarity.
=> feat(notif): group by grouping rather than owner

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt
"Deprecated" is only for the UI. We should still clean in those regions
=> fix(regions): clean in depricated regions

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisTaskTrackingRepository.kt
Can reproduce the NPEs locally when I delete individual resource keys from my local repository. Will look into what is actually happening, but for now this logs an exception and moves on.
=> fix(resource): if not in redis, don't throw NPE

swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/TestResourceTypeHandler.kt
Making the tests easier to read, refactoring the test resource type handler to a separate class, removing boilerplate test resource type handler code and providing some testing methods.
=> chore(test): refactor resource type handler test

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/model/AmazonResource.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandler.kt
Adding functionality to delete snapshots through orca
=> feat(snapshots): actual deletion of snapshots

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- update tag key to `resourceType`
=> fix(metrics): Update key used in tag

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- increment counter where resources are excluded
=> fix(core): Ensuring excluded resources are counted properly

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- fix candidateCounter with respect to maxItemsToProcess
=> fix(core): Ensuring maxItemsToProcess is respected

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt
- refactor method to not pass a null value
- added a metric to track redis failure for debugging
=> fix(*): fixing npe while getting data from redis

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt
- tracking a marshalling exception
=> chore(redis): add log for debugging

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshot.kt
- added equals/hashcode to snapshot data class
=> chore(snapshot): Specify equals/hashcode in data class

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonSnapshotProvider.kt
- ensuring the local retrySupport wrapped functions are used
=> fix(snapshot): Use retrySupport wrapped functions

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAutoScalingGroupProvider.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/tagging/OrcaTaggingService.kt
- Wrap calls to allow anonymous calls
=> fix(header): Wrap calls to allow anonymous calls

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/tagging/EntityTag.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/tagging/ResourceEntityTagger.kt
- update tags to include `documentation` link if specified in config
- update opt out link to include `namespace` and `resourceId`
=> fix(tagging): Misc updates to alert message

README.md
=> FIX - Grammar mistaker

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaImagesUsedByInstancesProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/Rules.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceOwnerResolver.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceTrackingManager.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/tagging/ResourceEntityTagger.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/TestResourceTypeHandler.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisTaskTrackingRepository.kt
I want to disable debug logs in production, so swept through the logs to and demoted some to debug.
Please let me know if you disagree with any of these.
=> chore(logs): changing level of some logs

build.gradle, settings.gradle, swabbie-bom/swabbie-bom.gradle
This simplifies downstream dependency management
=> feat(swabbie-bom): publish swabbie-bom

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/BaseImageLabelsExclusionSupplier.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/TemporalTagExclusionSupplier.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/exclusions/AmazonTagExclusionPolicyTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/WorkConfiguratorTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/exclusions/AccountExclusionPolicyTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicyTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/exclusions/LiteralExclusionPolicyTest.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicyTest.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisTaskTrackingRepositoryTest.kt
- Use a `Set` for merging instead of a `List` to remove dupes in attributes and exclusions
=> feat(exclusions): Fix exclusion merge function

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManager.kt
- fix the oops on the condition
=> fix(queueManager): Should empty queue when swabbie is disabled

README.md
- Update readme to remove the mention of agents
- Added some notes on queue usage
=> chore(readme): Remove mentions of agents

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkProcessor.kt
- only pop a workitem of the queue that can be worked on
=> fix(queueProcessor): Only accept work if you can do it

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkProcessor.kt
- fixing this as it would thrash redis with lock requests
=> fix(queueProcessor): Moving lock block out of loop

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- Passing `spinnakerWebUrl` to echo , to construct resourceUrl while generating email notifications
- Ref https://github.com/spinnaker/echo/pull/597
=> fix(notification): Update notification context with spinnaker webUrl

INTERNALS.md, README.md
I tried to capture both code and how to think about Swabbie.
=> chore(docs): add internals doc

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/Rules.kt
=> fix(asg): Remove extra whitespace in rule summary

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepositoryTest.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepositoryTest.kt
- tracking failures to read data from the database
=> chore(metrics): Adding some db failure metrics

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/tagging/ResourceEntityTagger.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManagerTest.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/TestingController.kt
- passing a human readable date for echo swabbie email template
=> chore(notifications): Ensure deletion date is passed to echo

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/AmazonTagExclusionPolicy.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/exclusions/AmazonTagExclusionPolicyTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicy.kt
- Change Exclusion.Attribute.value from `List<String>` to `List<Any>`
=> fix(exclusions): Changing Exclusion attribute value type

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
- remove unnecessary bulk unmarking
- fix test with previous false positive
=> fix(core): Removing bulk unmarking of marked resources

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt
- ensure tags are parsed correctly by fixing the type value to be Any
=> fix(core): Tag values as Any

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManager.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisNotificationQueue.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisWorkQueue.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisNotificationQueueTest.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisWorkQueueTest.kt
- moved track method for queues to respective impl
=> refactor(core): Move queue metrics to queues

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt
- if not specified in config this default will apply
=> chore(notifications): Update default interval to every 5mins

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt
=> fix(notifications): Fix default schedule value

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/ExpiredResourceRule.kt
- remove extra `$`
- reformat rule message
=> fix(rule): Fix tag rule message

swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaTaskMonitoringAgent.kt
- remove unnecessary eventing in orca task agent
=> fix(events): Dont resend additional events

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSenderTest.kt
- updated to filter out opted out and already processed resources
=> fix(notifications): Ensure skipping already opted/notified resources

swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
- properly calculate resource age using the clock
- updated test to use a clock
=> fix(core): Use clock when checking resource age against maxAge

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
=> fix(exclusion): Fixing not excluding on expired resource

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- updated to ensure the deleted resource is removed from the db
=> fix(core): Ensure resource is removed from db when deleted

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- updated to not count all marked resources from the database
=> fix(core): Fixing number of marked resources counter

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/TestResourceTypeHandler.kt
- Updated to eval resource against config specified rules
- falls back on default behavior if not specified in config
- BONUS: Basic support for AND & OR operators to allow rules composition
=> feat(core): Allow to define enabled rules in configuration

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- sort candidates by create stamp
=> enhancement(handler): Ensuring candidates are sorted

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandlerTest.kt, swabbie-test/src/main/kotlin/com/netflix/spinnaker/swabbie/test/WorkConfigurationTestHelper.kt
- clean out some TODOs
- decouple handler tests from rules
=> chore(test): Cleaning up tests

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/Rules.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/DisabledLoadBalancerRuleTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroLoadBalancerRuleTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Dates.kt
- added test case for optional parameter
=> fix(rules): Fixing disabled asg test

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/rules/Rules.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/rules/AttributeRuleTest.kt
- added an attribute rule that would apply if specified parameters match
the resource attributes
=> feat(rules): Attribute Rule

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicy.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicyTest.kt
- remove unused logic for composite matching
=> chore(allowlist): Clean out unused code

swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicy.kt
- fixed bug on applications being improperly matched against exclusion values
=> fix(exclusions): Fixing application exclusion

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/rules/Rules.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/TestResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/rules/AttributeRuleTest.kt
- updated attributes matching to handle non strings properties
=> improvement(attributesRule): Handling non strings in attributeRule

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepository.kt
- return null right away if state is null
=> chore(redis): Return null on null state string

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt
- Fixed a bug where the provider level exclusions were being merged onto
- Should be adding to the resource type level
=> fix(exclusion): Should be adding the resource type level exclusions

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/AmazonLaunchConfigurationHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/LaunchConfiguration.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/launchconfigurations/AmazonLaunchConfigurationHandlerTest.kt
- added launch configs support
=> feat(aws): Adding launch configurations cleanup support

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt
- make global dryRun overrideable
=> fix(config): Make dryRun overrideable at resource level

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandler.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisTaskTrackingRepository.kt
- common task logging for handlers
=> chore(logging): Consolidating task info log in one place

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManager.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisWorkQueue.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisWorkQueueTest.kt
- updated to move queue metrics to workManager
=> chore(metrics): Cleaning up queue metrics

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisNotificationQueue.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisNotificationQueueTest.kt
- cleaning up notification metrics
=> chore(metrics): Cleaning up notification metrics

README.md, docs/swabbie.yml
=> chore(docs): Updating docs

docs/swabbie.yml
- fix attributeRule parameters. they are key pairs.
=> chore(*): fix config yml template

docs/swabbie.yml
=> chore(docs): Update swabbie.yml template

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/Rules.kt
=> chore(*): Remove unused IS_BASE_OR_ANCESTOR

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/AWS.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
=> fix(aws): Filtering out public amis in vanilla

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt
- fixed an NPE when checking for server group references
=> fix(*): Fixing npe in elb handler

swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepository.kt
- fixed upsert to return the passed state rather than throwing
=> fix(state): Fixing upserting a state

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/rules/Rules.kt
- attribute's rule has a generic summary, adding a way to specify that in config
=> fix(attributeRule): Add optional description

docs/swabbie.yml
=> chore(docs): Update swabbie.yml

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSenderTest.kt
- ensure not sending duplication notifications
=> fix(notifications): Deduping notifications

CODEOWNERS
I'm going to remove myself as a code owner, since I no longer work on swabbie.
=> chore(codeowners): remove emjburns

gradle.properties
Revert to previous version of kork.
=> fix(misc): move to previous version of kork

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/CacheStatus.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Cacheable.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaTaskMonitoringAgent.kt
- Moved scheduling logic to CacheStatus.kt
- cleaned out the shutdown logic. not needed
- Upped interval for cache status check
- removed the discovery logic in the task monitor agent that was killing the scheduling thread
=> fix(*) Fixing cache scheduling failure

swabbie-aws/swabbie-aws.gradle, swabbie-clouddriver/swabbie-clouddriver.gradle, swabbie-core/swabbie-core.gradle, swabbie-echo/swabbie-echo.gradle, swabbie-front50/swabbie-front50.gradle, swabbie-orca/swabbie-orca.gradle, swabbie-retrofit/swabbie-retrofit.gradle, swabbie-test/swabbie-test.gradle
- replaced compile scope with implementation
=> chore(dependencies): Remove deprecated compile scope in gradle files

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/AWS.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroup.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/Edda.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/EddaService.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchtemplates/AmazonLaunchTemplate.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchtemplates/AmazonLaunchTemplateHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/launchtemplates/AmazonLaunchTemplateHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt
- added launch templates handler
=> feat(aws): Launch templates support

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt
Missed some configuration bits when I added deleteSpreadMs in https://github.com/spinnaker/swabbie/pull/542
=> fix(core): Add deleteSpreadMs config to CloudProviderConfiguration and pass to WorkConfigurator

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt
Fix image cleanup logic for images using launchTemplate
=> fix(image): Fix image cleanup logic for images using launchTemplate

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt
I didn't RTFM the first time around.
=> fix(core): Change lastMarked metric to use AGE function
