spinnaker/swabbie

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/LockingService.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/LockingConfiguration.kt
- also prefer bean creation in config for locking service
=> fix(locking): duration in millis and not seconds

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt
- fixed an issue where a candidate would be marked over and over
- refactored scheduled agent to add a delay
- refactored lock key to only consider work namespace
=> fix(mark): Should not mark a resource already marked

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImage.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/Rules.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/instances/AmazonInstance.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/LaunchConfiguration.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-edda/src/main/kotlin/com/netflix/spinnaker/swabbie/edda/EddaService.kt, swabbie-edda/src/main/kotlin/com/netflix/spinnaker/swabbie/edda/providers/EddaAmazonImageProvider.kt, swabbie-edda/src/main/kotlin/com/netflix/spinnaker/swabbie/edda/providers/EddaInstanceProvider.kt, swabbie-edda/src/main/kotlin/com/netflix/spinnaker/swabbie/edda/providers/EddaLaunchConfigurationProvider.kt
- added `OrphanedImageRule` to look for unused images
- rule looks to see if image is referenced by instances & launch configs
- looks to see if the current image has siblings in other accounts
=> feat(Images): Adding support for scanning Images

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
- leveraging a channel to pass deleted resources for further processing
- partitioning the list of items to delete based on configuration
- updated test to state invocation times rather than an upper limit
- This paves the way for a PR to update Image handler to batch deletes
=> refactor(*): Add basic support for batching deletes

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/AmazonTagExclusionPolicy.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/TemporalTagExclusionSupplier.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/exclusions/AmazonTagExclusionPolicyTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt
- temporal tags should exclude based on elapsed time with createTs
- ^\d+(d|m|y)$ is the pattern to match
- tags (ttl|expires|expiration_time) value matching pattern ^\d+(d|m|y)$
- parsed value is compared against createTs of the resource
=> feat(exclusions): Adding support for temporal tags

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
- separates fetching candidates from checking references
- step in stone PR to cleanup the delete function
=> refactor(*): Adding a preprocess fx to deal with checking references

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
- this fixes a regression due to refactoring
- need to be able to exclude/whitelist by owner
- to allow exclusion/inclusion by resource owner, that field needs to be computed before applying policies
=> fix(exclusions): Should resolve owners before running exclusion policies

gradle.properties, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
Upgrade kotlin version
Add a slim option for marked resource which gives you the identifying info and violations but not the whole resource object. This is the default. Get the full details by going to `https://localhost:8088/resources/marked?expand=true`
Also adding an endpoint to get a single marked resource `https://localhost:8088/resources/marked/{namespace}/{resourceId}`
=> feat(controller): slim for resources/marked exists as default

swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
Adding some useful apis to drill down into marked resources. this separates by namespace so you can look at all images in an account and region or whatever you'd like
=> feat(controller): get marked resources by namespace

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- fixed a stupid but deadly bug on candidate exclusion
- should not be grabbing the same element over in the filter
=> fix(handler): Fixing bug on excluding a candidate

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt, swabbie-web/src/test/kotlin/com/netflix/spinnaker/swabbie/web/ResourceControllerTest.kt
Adding `evaluateCandidate` method, exposed via api, to grab a single resource and then run it through the marking logic.
Hopefully this will be useful when checking rules so that we can on-demand run the `preProcessing` logic and ensure that a resource is marked or not marked.
=> feat(mark): api to see if resource would be marked

build.gradle, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/Rules.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/instances/AmazonInstance.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/LaunchConfiguration.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-aws/swabbie-aws.gradle, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/repository/ResourceUseTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisTaskTrackingRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepositoryTest.kt, swabbie-redis/swabbie-redis.gradle
Add a `ResourceUseTrackingRepository` to record when we see an image in use, and what server group that is a part of. 
Updated `AmazonImageHandler` to record what resource (server group) we saw an image used by.
Add ` outOfUseThresholdDays: 30` config option to control how long a resource can be unused for before we consider it able to be deleted (and mark it): 
```yaml
swabbie:
outOfUseThresholdDays: 30
```
Update the `OrphanedImageRule` to respect the allowed out of use period.
=> feat(rules): track when we saw an image in use last

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
Removing O(n^2) image sibling checking by pre-processing image using hash maps, then checking for keys in those.
Adding a 'numMarked' endpoint to easily see how many resources have been marked.
Bypassing the "last seen" check when outOfUseThreshold is set to 0.
=> fix(image): faster sibling check using maps

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/exclusions/AllowListExclusionPolicyTest.kt
- adding javadocs
- adding (and logging) a reason for why something is unmarked
- removing resources that no longer exist from the marked database before we run the mark cycle. This makes it easier to view swabbie's list of marked resources, since after a resource is deleted not using swabbie, swabbie will update the state it has.
- add an allow list test for an example
=> feat(mark): removing mark of deleted resources, comments

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/OnDemandMarkData.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/repository/ResourceUseTrackingRepository.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepositoryTest.kt
Making sure that if we've never seen a resource in use we don't mark it as SEEN_IN_USE. That way, when Swabbie starts up, it can both track usage and delete resources that we've never seen in use (like the old amis)
Storing the last seen info with marked resources, so that we can send the information in email notifications to make the more useful.
Sending the resources to echo as their `.slim()` version. We actually don't even need that much data, but I'll pair it down later. We're only rendering the good bits in the email.
=> feat(lastSeen): adding last seen info to markedResource

build.gradle, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaImagesUsedByInstancesProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationCacheProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/instances/AmazonInstance.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-clouddriver/src/main/kotlin/com/netflix/spinnaker/swabbie/clouddriver/ClouddriverAccountProvider.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Cacheable.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/CachedViewProvider.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exception/CacheSizeException.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exception/StaleCacheException.kt
Creates singleton cache, useful for having an object that you want to refresh.
Use this singleton cache in the edda caches (and refactor those to not be `@Lazy`).
Update the `checkReferences(..)` logic in `AmazonImageHandler` to check if an image is used in any launch config in any account, then check if the image is used by any images in any account. 
Rip out the siblings check, as it is no longer needed because we are checking the use in all accounts.
=> Better in use checking for images

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationCacheProvider.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
Unmark all resources that no longer qualify for a run of marking.
Previously, if a resource was marked and then later qualified to be excluded, the resource would stay marked.
Now, the marked resources should always reflect what currently qualifies.
=> Unmark if excluded

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaEndpointProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaImagesUsedByInstancesProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationCacheProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/BaseImageLabelsExclusionSupplier.kt, swabbie-clouddriver/src/main/kotlin/com/netflix/spinnaker/swabbie/clouddriver/ClouddriverAccountProvider.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Cacheable.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/services/DynamicPropertyService.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationCache.kt
In memory caches were only getting refreshed once.
The in memory caches needed to have a function that would refresh the caches, not be passed an object on startup.
=> fix(cache): load new caches every refresh

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationCacheProvider.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt
We were storing two sets of launch config data. Turns out we only need one set, organized by ami.
@robzienert we're only storing the data we need (https://github.com/spinnaker/swabbie/blob/master/swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/LaunchConfiguration.kt#L28), not a ton extra.
=> feat(cache): remove info we don't need about launch configs

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ScheduleTest.kt
Since swabbie runs on a schedule, the time it schedules the deletion should reflect that schedule. That way, when we notify people, no one is concerned that we are deleting things on a Saturday.
=> feat(schedule): deletion timestamp in schedule

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/discovery/DiscoveryPollingConfiguration.kt
Before, `NoDiscoveryApplicationStatusPublisher` would always be injected.
=> fix(discovery): make discovery activated work

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/MetricsSupport.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt
Ensuring that an exception thrown during execution (for example, during `doMark()`) gets surfaced and logged, and also increments a metric.
Also adding try/catch around scheduled to ensure that it gets rescheduled even if an exception is thrown.
=> fix(agents): surface exceptions, incr metric

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/CacheStatus.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Cacheable.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceSoftDeleteAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgentTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgentTest.kt
Before the agents start to mark a resource, all caches should fill. This PR adds support for that.
=> feat(cache): wait for caches to fill before working

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/CacheStatus.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceUseTrackingRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepositoryTest.kt
Bug: when hydrating, the redis repositories would only return the first `REDIS_CHUNK_SIZE` resources. This fixes that problem.
=> fix(redis): hydrating all values not just first 100

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/model/AmazonResource.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/exclusions/ExclusionPolicy.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Account.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Application.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/utils/ApplicationUtils.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceOwnerResolverTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManagerTest.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategy.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicy.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategyTest.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationExclusionPolicyTest.kt, swabbie-test/src/main/kotlin/com/netflix/spinnaker/swabbie/test/TestResource.kt
We can't parse app name from image name. We can only parse package name.
This PR introduces a "grouping" field on an excludable (an image, an application), and defines the value and what type it is. For example, a deb called "spinredis-server-0.0.1" would be grouped by the `PACKAGE_NAME` `spinredis-server`. Because this grouping is not `APPLICATION`, the `Front50ApplicationExclusionPolicy` cannot provide any ownership about it, and now returns null (null == should not exclude).
This grouping is used when we group resources together (to send notifications) and to submit task to orca (for deletion, now all tasks will show up in the swabbie app).
For things that don't have grouping (resources marked before this PR is merged), tasks will appear under "swabbie" app and emails will be sent with …
=> feat(grouping): add grouping (like app) to resources

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandler.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
We want to let people opt out (aka tag their image with `"expiration_time":"never"`) even if we haven't marked it yet. 
This updates the opt out api to add that functionality.
=> feat(optOut): opt out resource even if we didn't mark it yet

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaTaskMonitoringAgent.kt
Remove timeout override for orca delete task (because we are no longer monitoring delete: https://github.com/spinnaker/orca/pull/2520). 
Updating log message in orca task monitor to be shorter.
=> chore(timeout) remove orca task timeout for delete

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceCleanerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgent.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/NotificationAgentTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/ResourceMarkerAgentTest.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaTaskMonitoringAgent.kt
Have swabbie work decision backed by a fast property (`swabbie.work` as boolean).
Have the max batch size backed by fast properties (`${namespace}.maxItemsProcessedPerCycle`)
=> feat(fastProps): work and maxBatchSize fast props

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandler.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/AdminController.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ControllerUtils.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
We may want to update the deletion time of a bunch of resources, like if we want to speed up or slow down deletion of resources.
This admin endpoint lets you update the deletion time for the oldest `numResources` resources to a value of `retentionS` seconds from now. It operates in a single namespace.
=> feat(deleteTime): recalculate time for some resources

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/Notifier.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt
Some resources need to be cleaned too often to notify users every time we delete something. Janitor monkey did not notify for image clean up, so this PR adds that functionality into swabbie.
The default behavior is the same. However, if you set 
``` 
notifications:
enabled: true
required: false
```
the notification agent will run but no notifications will be sent. 
This behavior is a little bit convoluted - a cleaner solution would be to have deletion not depend on notifying for all resources. However, that would be a large change to the assumptions of Swabbie (something must be notified before it was deleted. This PR keeps the same assumptions and adds support for not notifying with minimal changes.
There are also some indentation changes because I ran the auto-formatter.
=> feat(notify): notifications not always required

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/MetricsSupport.kt
Periodically I'll see a ton of resources unmarked for no reason. When I look in detail at them, I don't see that they were used. Just that they suddenly "don't qualify to be deleted" anymore. My working theory is that sometimes we get back a subset of data from edda or from redis, and that causes us to wipe anything we don't know about.
This PR adds a configurable max number of resources to unmark at once so that if this happens occasionally we won't unmark all our resources. 
It also adds some logging and metrics around the number marked so that I can further debug.
=> fix(mark): only unmark a config number at once, add totalMarkCount metric

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/EddaService.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonSnapshotProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImage.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshot.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/SnapshotRules.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Dates.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceTrackingManager.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/repository/UsedResourceRepository.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/repository/UsedSnapshotRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisUsedResourceRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisUsedSnapshotRepository.kt
Mark snapshots. This will only mark things that fit the pattern of auto-snapshotted during a netflix bake. 
There's also a change to the image handler. Some background: AMIs contain a mapping to snapshots. Snapshots do not contain the mapping of what image they're a snapshot of. The change: as we go through the AMIs we record what snapshots they have, with at TTL of 2 days. We use this information in the snapshot handler to not delete snapshots which have been recorded here aka the image still exists for this snapshot.
Coming: deletion of snapshots via an orca task. It's marked as to-do right now.
An important note: you can't delete a snapshot of an ebs volume when the image it was taken from exists. So, there is really no harm in 'accidentally' deleting the snapshot.
=> feat(snapshots): snapshot handler to first pass

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- We log the summary of number of candidates processed , adding these numbers as metrics to get better visibility into the health of the system
=> Add metrics for number of candidates processed

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroup.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImage.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/instances/AmazonInstance.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/LaunchConfiguration.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonElasticLoadBalancer.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroup.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceOwnerResolverTest.kt, swabbie-front50/src/test/kotlin/com/netflix/spinnaker/swabbie/front50/ApplicationResourceOwnerResolutionStrategyTest.kt, swabbie-test/src/main/kotlin/com/netflix/spinnaker/swabbie/test/TestResource.kt
- add explicit equals and hashcode to data classes
- fix a bug on Resource.equals
- use TestResource from test where possible instead of creating new ones
=> fix(*): Override hashcode, equals in resource data class

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceTrackingRepository.kt
- Simplify lock to reuse version
- Moved unmarkResources inside the try..catch block
- Removed debug log
- Adjust readMarkedResource api param as nullable
=> chore(*): Update lock config

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaEndpointProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/exclusions/BaseImageLabelsExclusionSupplier.kt, swabbie-clouddriver/src/main/kotlin/com/netflix/spinnaker/swabbie/clouddriver/ClouddriverAccountProvider.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/swabbie/front50/Front50ApplicationCache.kt
- Explicitly allow anonymous calls for dependent services , This should address the issue of warning log messages that were seen.
=> fix(misc) : Fix to allow anonymous calls

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaImagesUsedByInstancesProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationCacheProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/model/AmazonResource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Cacheable.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/Main.kt
- Couple of update to address boot2 kabab casing 
- Wrap calls to allow `allowAnonymous` requests
- Add `@EnableScheduling` to allow `@Scheduled` to work again ( not entirely clear how this was working before the boot update)
=> fix(*) : Misc fix for boot2 update

build.gradle, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
* Bumping kork to try stay current.
* Adding a log statement with the details of a resource to see if we think it has been seen recently or something when it gets unmarked.
=> fix(log+kork): bump kork and add logs for unmark

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- wrongly placed the unmark block inside of a loop
- moved the unmark block outside of the loop and record failure metric
=> fix(core): fixing unmarking oops

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonElasticLoadBalancerProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonImageProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonSecurityGroupProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAmazonSnapshotProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaApiSupport.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaAutoScalingGroupProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaInstanceProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/providers/EddaLaunchConfigurationProvider.kt
- follow up to #203 , updated all `Edda` Providers
=> fix(header): Make request as anonymous

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandler.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaService.kt
Adding a wait stage before we delete the snapshot so that we stagger deletes across the entire clean interval. This will help us not blow through rate limits, and delete more things in a clean run.
If this is successful here, it's super easy to add to delete image.
=> feat(snapshots): add wait before delete

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgent.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/agents/ScheduledAgentTest.kt
- remove double scheduling after caches are loaded
- refactored ScheduledAgent#timeToWork to not include off hours
- if off hours are needed, the config can be explicitly updated
=> fix(schedule): Fix for swabbie scheduling

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- We were not publishing `DeleteResourceEvent` for delete action , adding that to take care of metrics issue.
=> fix(metrics): Fix delete metrics

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandler.kt
We lost this config property when we switched to a work queue. Giving this important property a proper name and default value.
=> fix(jitter): update config property for random jitter interval

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/config/AwsConfiguration.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ControllerUtils.kt
the image handler was broken because we were conditionally wiring things wrong. Removing the conditionals since they're not based on config properties and should always be wired in for now.
=> fix(images): actually run the image handler

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/config/AwsConfiguration.kt
In theory we'd like to only have the caches needed for each resource group populate. In practice, there's some mixing of cache use. This PR fully removes the conditional beans so that we can enable server groups again.
In the future we need to re-evaluate this cache sharing or clearly have required caches for each resource type.
=> fix(serverGroups): make all caches required

swabbie-core/src/main/kotlin/com/netflix/spinnaker/config/SwabbieProperties.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfigurationTest.kt
This adds the ability to configure which actions you want to run for each resource. This allows you to not run delete for some or all the resources you're marking (like, say, locally).
=> fix(work): allow you to configure which actions run

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/caches/ImagesUsedByInstancesProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/caches/LaunchConfigurationCacheProvider.kt
We need to update each set instead of replacing it so that we keep track of all image use info, not just for the last account we check.
=> fix(caching): add to sets instead of replace whole set

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/repository/ResourceStateRepository.kt, swabbie-redis/src/main/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepository.kt, swabbie-redis/src/test/kotlin/com/netflix/spinnaker/swabbie/redis/RedisResourceStateRepositoryTest.kt, swabbie-redis/swabbie-redis.gradle, swabbie-test/swabbie-test.gradle, swabbie-web/src/main/kotlin/com/netflix/spinnaker/swabbie/controllers/ResourceController.kt
We use the resource state repository to track when resources are opted out/marked/notified/deleted. Right now we never remove any resources from it. We've deleted a lot of things, and it would be nice to remove them so that we don't have to deal with weird old data.
This PR adds a cleaning function that runs every 5 minutes to remove deleted resources from the resource state repository.
=> Clean state repository

swabbie-aws/swabbie-aws.gradle, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/CacheStatus.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/tagging/ResourceEntityTagger.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkProcessor.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManager.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManagerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/events/ResourceTrackingManagerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/work/WorkProcessorTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManagerScheduleTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManagerTest.kt, swabbie-core/swabbie-core.gradle, swabbie-orca/swabbie-orca.gradle, swabbie-redis/swabbie-redis.gradle, swabbie-test/src/main/kotlin/com/netflix/spinnaker/swabbie/test/NoopCacheStatus.kt, swabbie-test/src/main/kotlin/com/netflix/spinnaker/swabbie/test/WorkConfigurationTestHelper.kt, swabbie-test/swabbie-test.gradle
Swabbie was working when it was disabled in discovery. This PR fixes that functionality so that swabbie doesn't work when it's down in discovery, and also adds a test for that case.
I also added a testing util and refactored some of the tests.
=> Rest when disabled

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroup.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/Rules.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceDisabledServerGroupRuleTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/ZeroInstanceInDiscoveryDisabledServerGroupRuleTest.kt
- remove misleading classifiers for disabled. use fields instead
- fix test
=> fix(serverGroup): Fixing asg rules and handler

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt
- fixed to not expire if temporal tag has value "never"
- Updated to not exclude an expired resource
=> fix(exclusion): Do not excluded expired resources

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt
- Shuffling candidates to give a semi equal chance for a candidate to be eval'd
- Sorting by createTs can result in the same subset of candidate to be eval'd
pver and over.
=> fix(core): Shuffle candidates before processing

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt
- simplify merging: initial assumption no longer applies
- no need for fancy merging attributes
=> chore(exclusion): Simplify exclusion merging

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandlerTest.kt
- updated snapshot handler to not be specific to netflix
* prefer using exclusions or rules in config than hard coded
* use AttributeRule if need to match against the snapshot attributes
- null descriptions should be allowed and should be excluded by policy in config
=> chore(*): Generify snapshot handler

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/WorkConfigurator.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Account.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/WorkConfiguratorTest.kt
- updated default values to empty account
- made Resource.getProperty public
- updated work configurator to account for the placeholder account
=> chore(*): Allow a placeholder account with the empty account

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/notifications/NotificationSender.kt, swabbie-echo/src/main/kotlin/com/netflix/spinnaker/swabbie/echo/EchoNotifier.kt, swabbie-echo/src/test/kotlin/com/netflix/spinnaker/swabbie/echo/EchoNotifierTest.kt
- remove retrySupport use from echo notifier
- only allow one worker to send notifications at a time
=> fix(notifications): Preventing resubmitting notifications

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Dates.kt
Some additional changes:
* Added a new format to `Dates.kt` because the Java 11 JRE returns nanoseconds for `LocalDateTime.now()`, so a few tests were failing. Another option is to use `LocalDateTime.now().truncateTo(MILLIS)` but this seemed more future-proof to me. Let me know if you'd prefer a different fix, however.
=> chore(java11): Compile with Java 11 (but targeting Java 8)

swabbie-core/swabbie-core.gradle
An upcoming kork bump changes a number of dependencies from api to implementation when comsumers shouldn't need these on the compile path. This commit explicitly adds in dependencies that will no longer be transitively included.
=> chore(dependencies): Add explicit dependency

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt
- updated to use image names because orca expects that and not imageId
=> fix(aws): Fixing tagging ami during optout

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/config/AwsConfiguration.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/AWS.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/caches/AmazonLaunchTemplateVersionCache.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/caches/LaunchTemplateVersionsCacheProvider.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/Edda.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/EddaService.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/Rules.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchtemplates/AmazonLaunchTemplateVersion.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt
- added an in-memory cache for use in the imageHandler
- updated imageHandler to check for images used by launch templates
=> feat(aws): Checking for launch template references in imageHandler

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchconfigurations/AmazonLaunchConfigurationHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/launchtemplates/AmazonLaunchTemplateHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/loadbalancers/AmazonLoadBalancerHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/securitygroups/AmazonSecurityGroupHandler.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/snapshots/AmazonSnapshotHandler.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/autoscalinggroups/AmazonAutoScalingGroupHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/launchconfigurations/AmazonLaunchConfigurationHandlerTest.kt, swabbie-aws/src/test/java/com/netflix/spinnaker/swabbie/aws/launchtemplates/AmazonLaunchTemplateHandlerTest.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/AbstractResourceTypeHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/Resource.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/model/WorkConfiguration.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/ResourceTypeHandlerTest.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/TestResourceTypeHandler.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/swabbie/orca/OrcaService.kt
Previously, we had jitter across a fixed range that was added to these deletes.  This still ended up with deletes being clumped into a fairly tight window, which caused AWS rate limiting in downstream services.  This proposes to delete across an evenly distributed time window.
=> fix(core): Evenly distribute delete resources across the configured delete spread time divided by the total number of resource partitions

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/Edda.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/EddaService.kt, swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/images/AmazonImageHandler.kt, swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManager.kt, swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManagerTest.kt
- Additionally, since the total number of launch configs will diminish over time we also need to compare the total number of launch templates + launch configs when checking if images are used by launch configurations
- Removes an unnecessary sleep (which would be interrupted, throw an error, add noise to the logs) - now just check if caches are loaded as part of the normal monitor `WorkQueueManager#monitor` cycle
=> fix(launchTemplates): Pull aws launch template version from edda

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/events/ResourceStateManager.kt
We want to alert when swabbie is no longer marking resources as a result of a regression
or similar. This adds a new metric to record the last time a resource was marked, making
the alert much easier (or possible) to craft.
=> feat(core): Track last resource marked timestamp

.mergify.yml
since it's deprecated.  See https://blog.mergify.com/strict-mode-deprecation/
=> chore(mergify): stop using strict mode in mergify

swabbie-clouddriver/src/main/kotlin/com/netflix/spinnaker/config/ClouddriverConfiguration.kt, swabbie-echo/src/main/kotlin/com/netflix/spinnaker/config/EchoConfiguration.kt, swabbie-front50/src/main/kotlin/com/netflix/spinnaker/config/Front50Configuration.kt, swabbie-orca/src/main/kotlin/com/netflix/spinnaker/config/OrcaConfiguration.kt, swabbie-retrofit/src/main/kotlin/com/netflix/spinnaker/swabbie/retrofit/SwabbieRetrofitConfiguration.kt, swabbie-retrofit/swabbie-retrofit.gradle
The `X-SPINNAKER-USER` header will be set to the value of `ok-http-client.spinnaker-user` (defaulting to `swabbie@spinnaker.io`), and `X-SPINNAKER-ACCOUNTS` will be contain all the accounts that are configured in Swabbie. This is already supported for the Edda client, but not for calls to Echo, Front50, Orca or Clouddriver, so this PR just change the different service classes to use the same retrofit/okHttpClient as Edda and adds the `X-SPINNAKER-ACCOUNTS` header as well. These headers are needed if you are trying to clean up any protected AWS accounts.
=> feat(auth): Support for spinnaker user

.github/workflows/release.yml
to avoid warning messages like
Run echo ::set-output name=REPO::${GITHUB_REPOSITORY##*/} Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore(gha): replace deprecated set-output commands with environment files

gradle.properties
The release-1.30.x branch didn't exist when the automation in kork tried to make this, so doing it manually.
=> chore(dependencies): bump korkVersion

swabbie-aws/src/main/kotlin/com/netflix/spinnaker/config/AwsConfiguration.kt
Regional STS endpoints can be turned on or off, so there is no guarantee that `us-west-2` is enabled. However, `us-east-1` is special as it is the only regional endpoint that can't be turned off. This fixes the following error:
```
com.amazonaws.services.securitytoken.model.RegionDisabledException: STS is not activated in this region for account:01234567890. Your account administrator can activate STS in this region using the IAM Console.
```
=> fix(aws): Change default region to us-east-1

swabbie-core/src/main/kotlin/com/netflix/spinnaker/swabbie/Dates.kt
Swabbie started failing when parsing AMI image timestamp. Adding another pattern to the list of supported formats fixed the issue.
=> fix(core): Add another date format to the date parser
